name: Spring Boot Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@3.9.9

      - name: Build with Maven
        run: mvn clean install
