name: Spring Boot Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Install Maven 3.9.9
        run: |
            wget https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
            tar -xvzf apache-maven-3.9.9-bin.tar.gz
            sudo mv apache-maven-3.9.9 /opt/apache-maven-3.9.9
          
      - name: Set Maven 3.9.9 in PATH
        run: echo "export PATH=/opt/apache-maven-3.9.9/bin:\$PATH" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -DskipTests
